package com.example.proyectfinanzasinvisibles.frontend.ui

import androidx.compose.runtime.*

enum class Language {
    ES, EN
}

data class AppStrings(
    val appName: String,
    val home: String,
    val history: String,
    val goals: String,
    val ai: String,
    val settings: String,
    val dashboard: String,
    val weeklyLeak: String,
    val stealthLeak: String,
    val accumulatedWeekly: String,
    val intelligentDetection: String,
    val expenseDetected: String,
    val evade: String,
    val ignore: String,
    val spendingDistribution: String,
    val total: String,
    val recentActivity: String,
    val justNow: String,
    val editProfile: String,
    val logout: String,
    val language: String,
    val manageAccount: String,
    val selectLanguage: String,
    val alerts: String,
    val controlCenter: String,
    val noNotifications: String,
    val name: String,
    val surname: String,
    val birthDate: String,
    val email: String,
    val password: String,
    val confirmPassword: String,
    val login: String,
    val initialize: String,
    val needAccess: String,
    val alreadyInitialized: String,
    val fieldsRequired: String,
    val initializationFailed: String,
    val invalidCredentials: String,
    val passwordsMismatch: String,
    val silentAssistant: String,
    val activeNow: String,
    val monthlySummary: String,
    val leaksAvoided: String,
    val systemOptimizing: String,
    val activeChallenges: String,
    val viewAll: String,
    val daysWithoutLeaks: String,
    val projectedGoal: String,
    val savingPerspective: String,
    val weeklyMinorExpenses: String,
    val equivalenceServices: String,
    val directImpactBudget: String,
    val constantChangesResult: String,
    val createNewGoal: String
)

val SpanishStrings = AppStrings(
    appName = "FINANZAS INVISIBLES",
    home = "Inicio",
    history = "Historial",
    goals = "Metas",
    ai = "IA",
    settings = "Ajustes",
    dashboard = "DASHBOARD",
    weeklyLeak = "Resumen de\nFugas Semanales",
    stealthLeak = "FUGA SILENCIOSA",
    accumulatedWeekly = "Acumulado semanal en gastos menores",
    intelligentDetection = "DETECCIÓN INTELIGENTE",
    expenseDetected = "Se detectó un posible gasto innecesario.",
    evade = "Evadir",
    ignore = "Ignorar",
    spendingDistribution = "Distribución de Gastos",
    total = "TOTAL",
    recentActivity = "Actividad Reciente",
    justNow = "Ahora mismo",
    editProfile = "Editar Perfil",
    logout = "Cerrar Sesión",
    language = "Idioma",
    manageAccount = "Gestionar Cuenta",
    selectLanguage = "Seleccionar Idioma",
    alerts = "ALERTAS",
    controlCenter = "Centro de Control",
    noNotifications = "No hay notificaciones críticas pendientes.",
    name = "NOMBRE",
    surname = "APELLIDO",
    birthDate = "FECHA DE NACIMIENTO (DD/MM/AAAA)",
    email = "CORREO ELECTRÓNICO",
    password = "CONTRASEÑA",
    confirmPassword = "CONFIRMAR CONTRASEÑA",
    login = "INICIAR SESIÓN",
    initialize = "INICIALIZAR",
    needAccess = "¿NECESITAS ACCESO? INICIALIZA AQUÍ",
    alreadyInitialized = "¿YA INICIALIZADO? INICIA SESIÓN",
    fieldsRequired = "CAMPOS REQUERIDOS",
    initializationFailed = "FALLO AL INICIALIZAR",
    invalidCredentials = "CREDENCIALES INVÁLIDAS",
    passwordsMismatch = "LAS CONTRASEÑAS NO COINCIDEN",
    silentAssistant = "Asistente Silencioso",
    activeNow = "Activo ahora",
    monthlySummary = "RESUMEN MENSUAL",
    leaksAvoided = "Has evitado $1,200 en fugas este mes.",
    systemOptimizing = "El sistema está optimizando tus gastos.",
    activeChallenges = "Retos Activos",
    viewAll = "VER TODOS",
    daysWithoutLeaks = "días sin gastos hormiga",
    projectedGoal = "Meta: $90 proyectados",
    savingPerspective = "Perspectiva de Ahorro",
    weeklyMinorExpenses = "Gastos menores semanales",
    equivalenceServices = "Equivalencia en servicios",
    directImpactBudget = "Impacto directo en presupuesto",
    constantChangesResult = "\"Pequeños cambios constantes generan resultados visibles.\"",
    createNewGoal = "+ Crear nueva meta"
)

val EnglishStrings = AppStrings(
    appName = "INVISIBLE FINANCE",
    home = "Home",
    history = "History",
    goals = "Goals",
    ai = "AI",
    settings = "Settings",
    dashboard = "DASHBOARD",
    weeklyLeak = "Weekly Leak\nOverview",
    stealthLeak = "STEALTH LEAK",
    accumulatedWeekly = "Accumulated weekly in minor expenses",
    intelligentDetection = "INTELLIGENT DETECTION",
    expenseDetected = "Potential unnecessary expense detected.",
    evade = "Evade",
    ignore = "Ignore",
    spendingDistribution = "Spending Distribution",
    total = "TOTAL",
    recentActivity = "Recent Activity",
    justNow = "Just now",
    editProfile = "Edit Profile",
    logout = "Logout",
    language = "Language",
    manageAccount = "Manage Account",
    selectLanguage = "Select Language",
    alerts = "ALERTS",
    controlCenter = "Control Center",
    noNotifications = "No critical notifications pending.",
    name = "NAME",
    surname = "SURNAME",
    birthDate = "BIRTH DATE (DD/MM/YYYY)",
    email = "EMAIL",
    password = "PASSWORD",
    confirmPassword = "CONFIRM PASSWORD",
    login = "LOGIN",
    initialize = "INITIALIZE",
    needAccess = "NEED ACCESS? INITIALIZE HERE",
    alreadyInitialized = "ALREADY INITIALIZED? LOGIN",
    fieldsRequired = "FIELDS REQUIRED",
    initializationFailed = "INITIALIZATION FAILED",
    invalidCredentials = "INVALID CREDENTIALS",
    passwordsMismatch = "PASSWORDS MISMATCH",
    silentAssistant = "Silent Assistant",
    activeNow = "Active now",
    monthlySummary = "MONTHLY SUMMARY",
    leaksAvoided = "You have avoided $1,200 in leaks this month.",
    systemOptimizing = "The system is optimizing your spending.",
    activeChallenges = "Active Challenges",
    viewAll = "VIEW ALL",
    daysWithoutLeaks = "days without leaks",
    projectedGoal = "Goal: $90 projected",
    savingPerspective = "Saving Perspective",
    weeklyMinorExpenses = "Weekly minor expenses",
    equivalenceServices = "Equivalencia en servicios",
    directImpactBudget = "Direct impact on budget",
    constantChangesResult = "\"Small constant changes generate visible results.\"",
    createNewGoal = "+ Create new goal"
)

val LocalStrings = staticCompositionLocalOf { SpanishStrings }

@Composable
fun ProvideStrings(language: Language, content: @Composable () -> Unit) {
    val strings = if (language == Language.ES) SpanishStrings else EnglishStrings
    CompositionLocalProvider(LocalStrings provides strings, content = content)
}
